name: 'CoreWorkflow'
description: 'Generate tags according to core workflow'
inputs:
  trigger-build:  # id of input
    description: 'trigger a build workflow defined in the repository actions'
    required: false
    default: 'false'
outputs:
  new_tag:
    description: 'Generated tag'
  pre_release:
    description: 'Whether it is a release candidate'
runs:
  using: 'node20'
  main: 'dist/index.js'
