name: 'CoreWorkflow'
description: 'Generate tags according to core workflow'
#inputs:
#  milliseconds:  # id of input
#    description: 'number of milliseconds to wait'
#    required: true
#    default: '1000'
outputs:
  new_tag:
    description: 'Generated tag'
  pre_release:
    description: 'Whether it is a release candidate'
runs:
  using: 'node20'
  main: 'dist/index.js'
